ThayalanGR/react-fields-keeper

src/Examples/Example19_disable_bucket.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperRootBucket.tsx
added a flag to disable default assignment
=> feat(disable): added disabled bucket

src/Examples/Example22_bucket_accept_types.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx
feat(bucketTypes): added bucket types to restrict field assignment
#reviwer
@ThayalanGR
=> feat(bucketTypes): added bucket types to restrict field assignment

src/Components/ContextMenu.tsx, src/Components/index.ts, src/Components/utils.ts, src/Examples/Example18_suffix_node_support.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/index.css, src/index.ts
=> feat(SuffixNode): Implemented Suffix Node with Context Menu

src/Examples/Example24_filter_items.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperRootBucket.tsx
1. Added an optional prop to filter the all items.
2. In example 24, Faced an when we try to pin a group. Hence, created a set and checking whether group or id is present within the set.
3. Added a emptyDataMessage also
=> feat(rfk): Added filterItems in root bucket

src/Components/svgElements/Icons.tsx, src/Examples/Example24_accent_color.tsx, src/Examples/Example25_accent_color.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperProvider.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/FieldsKeeperSearcher.tsx, src/FieldsKeeper/fieldsKeeper.less
=> feat(TickAnnotation): Folder check Mark annotation implemented

src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/fieldsKeeper.less
=> feat(shuffling): Update shuffling functionality |  fix(collapse): update exp/collapse functionality

src/FieldsKeeper/FieldsKeeperBucket.tsx
=> fix(duplicates): Restricting duplicates when assigned witihin same bucket

package.json, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/fieldsKeeper.less, yarn.lock
We are using mark.js library for highlighting the text searched. 
1. Create a ref for the container where the text needs to be highlighted.
2. Create an instance of Mark by passing the container.
3. Clearing the previous highlight using unmark function and using the done callback we are passing the necessary args className: 'search-highlight', separateWordSearch: true, diacritics: true, caseSensitive: false.
4. If the query matches any text, highlighting takes place, else it removes the text highlight
=> feat(highlight): Implementation of Seach highlight

src/Components/index.ts
=> refactor(suffixNode): Export suffix node

package.json, src/Components/ContextMenu/ContextMenu.tsx, src/Components/ContextMenu/ContextMenuOption.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, yarn.lock
=> feat(suffixNode): update contextMenu using usePopper

src/Examples/Example26_Edited_Bucket_Label.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx
=> feat(EditedLabel): Edit field item label

src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/fieldsKeeper.less
=> fix(inputField): Editable Input field styling changes

src/Examples/Example12.tsx, src/Examples/Example18_suffix_node_support.tsx, src/Examples/Example20_folder_scope.tsx, src/Examples/Example21_prefix_node_support.tsx, src/Examples/Example23_disable_assignments.tsx, src/Examples/Example24_filter_items.tsx, src/Examples/Example25_accent_color.tsx, src/Examples/Example26_Edited_Bucket_Label.tsx, src/Examples/Example27_group_only_selection.tsx, src/Examples/Example28_nested_folder.tsx, src/Examples/Example3_grouping_items.tsx, src/Examples/Example4_custom_bucket_priority.tsx, src/Examples/Example5_disabling_fields.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): update linear structure in rfk

src/Examples/Example29_SourceId.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx
When a field is dragged from root bucket and dropped in fields bucket, we are changing the id of the fieldItem if allowduplicates is true.
=> feat(rfk): Implementation of Source Id

src/Examples/Example30_flat_group.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/fieldsKeeper.less, src/FieldsKeeper/utils.ts
=> feat(rfk): Flat group implementation

src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/fieldsKeeper.less
=> feat(rfk): Added custom styling for root and field buckets

src/Examples/Example31_CustomStyling.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/fieldsKeeper.less
=> fix(rfk): Group hover | custom styling example | folder icon issue

src/Examples/Example26_Edited_Bucket_Label.tsx, src/Examples/Example31_CustomStyling.tsx, src/Examples/Styling/Example31_CustomStyling.css, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/fieldsKeeper.less
=> fix(rfk): Bug fixes and stability changes

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): Prefix node not displaying when reserve space is false

src/Components/ContextMenu/ContextMenu.tsx, src/Examples/Example32_context_menu.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperProvider.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/FieldsKeeperSearcher.tsx, src/FieldsKeeper/fieldsKeeper.less
=> feat(rfk): context menu onclick , icon color

src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): Handled issue's related to expand/collapse and context menu for grp/flat grp

src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> feat(rfk): Implementation of sort based on folder

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): update custom className for padding

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): update custom styling for group header

src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/utils.ts
=> fix(rfk): update group functionality similar to powerbi

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): search issue for table name

src/FieldsKeeper/FieldsKeeperBucket.tsx
=> fix(rfk): Drop non-grp field between a group splits the group

src/FieldsKeeper/FieldsKeeperBucket.tsx
Reviewers : @ThayalanGR 
https://github.com/user-attachments/assets/f5b5f8b0-bc02-42ab-be1c-74063becfb81
=> fix(rfk): update group ordering

src/Examples/Example33_add_to_bucket.tsx, src/Examples/index.tsx, src/FieldsKeeper/FieldsKeeper.context.ts, src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/utils.ts
https://github.com/user-attachments/assets/34442be5-db61-4ac5-865b-560cba3ab17b
=> feat(rfk): Add fields to different buckets from suffix node

src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperRootBucket.tsx, src/FieldsKeeper/fieldsKeeper.less
=> fix(rfk): Adjust styling for datapane icons

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): update delimiter in root bucket

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): show check mark only for non node elements

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): update state functionality to avoid early return

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): update suffix node on hover

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): onfielditemclick is not getting called

src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperBucket.tsx
=> feat(rfk): introduce dragging flag in field bucket

src/FieldsKeeper/utils.ts
=> fix(rfk): update group order functionality

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
When showsuffixonHover is passed as false, the suffix node is not rendering.
=> fix(rfk): update showSuffixOnHover issue

src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> fix(rfk): added context menu at folder level

src/FieldsKeeper/FieldsKeeper.types.ts, src/FieldsKeeper/FieldsKeeperRootBucket.tsx
=> feat(rfk): hide folders using hidden props or classname
